# Generated by Django 5.0.3 on 2024-03-29 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedIn_url', models.URLField(unique=True)),
                ('gitHub_url', models.URLField(unique=True)),
            ],
        ),
    ]
