# Generated by Django 5.0.3 on 2024-03-29 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='about',
            field=models.TextField(default='hello'),
        ),
    ]
