# Generated by Django 5.0.3 on 2024-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('github_link', models.URLField()),
                ('demo_link', models.URLField()),
                ('video_url', models.URLField()),
            ],
        ),
    ]
