# Generated by Django 5.0.3 on 2024-03-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='email',
            field=models.CharField(default='favourokerri767@gmial.com', max_length=200),
        ),
    ]
